// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Living_Fountain;

[PrimaryKey("block", "lot", "phase")]
[Table("customers", Schema = "living_fountain")]
[Index("block", Name = "block")]
public partial class customer
{
    [Key]
    public int block { get; set; }

    [Key]
    public int lot { get; set; }

    [Key]
    public int phase { get; set; }

    [InverseProperty("customer")]
    public virtual ICollection<order> orders { get; set; } = new List<order>();
}