using System.Data;
using System.Windows.Controls;

public static class DataGridHelper
{
    private static readonly DatabaseHelper db = new DatabaseHelper();

    public static void LoadData(DataGrid dataGrid, string query, params string[] headers)
    {
        DataTable data = db.ExecuteQuery(query);
        dataGrid.ItemsSource = data.DefaultView;

        // Ensure that columns are generated before setting headers
        dataGrid.AutoGeneratedColumns += (s, e) =>
        {
            SetColumnHeaders(dataGrid, headers);
        };
    }

    public static void SetColumnHeaders(DataGrid dataGrid, params string[] headers)
    {
        for (int i = 0; i < headers.Length && i < dataGrid.Columns.Count; i++)
        {
            dataGrid.Columns[i].Header = headers[i];
        }
    }
}
