// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Living_Fountain;

[Table("employees", Schema = "living_fountain")]
[Index("emp_type_code", Name = "emp_type_code")]
public partial class employee
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(15)]
    public string employee_name { get; set; }

    [StringLength(1)]
    public string emp_type_code { get; set; }

    [ForeignKey("emp_type_code")]
    [InverseProperty("employees")]
    public virtual employee_type emp_type_codeNavigation { get; set; }

    [InverseProperty("deliverer")]
    public virtual ICollection<order> orders { get; set; } = new List<order>();
}