// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Living_Fountain.Models;

[Table("orders", Schema = "living_fountain")]
[Index("block", "lot", "phase", Name = "address")]
[Index("deliverer_id", Name = "employee")]
[Index("product_code", Name = "product")]
[Index("status", Name = "status")]
public partial class order
{
    [Key]
    public int id { get; set; }

    public int? block { get; set; }

    public int? lot { get; set; }

    public int? phase { get; set; }

    public DateOnly? date { get; set; }

    [StringLength(2)]
    public string product_code { get; set; }

    public int? quantity { get; set; }

    [Column(TypeName = "decimal(5, 0)")]
    public decimal? price { get; set; }

    public int? deliverer_id { get; set; }

    [StringLength(2)]
    public string status { get; set; }

    [ForeignKey("block, lot, phase")]
    [InverseProperty("orders")]
    public virtual customer customer { get; set; }

    [ForeignKey("deliverer_id")]
    [InverseProperty("orders")]
    public virtual employee deliverer { get; set; }

    [ForeignKey("product_code")]
    [InverseProperty("orders")]
    public virtual product product_codeNavigation { get; set; }

    [ForeignKey("status")]
    [InverseProperty("orders")]
    public virtual order_status statusNavigation { get; set; }
}