// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Living_Fountain.Models;

[Table("order_status", Schema = "living_fountain")]
public partial class order_status
{
    [Key]
    [StringLength(2)]
    public string code { get; set; }

    [StringLength(20)]
    public string status_desc { get; set; }

    [InverseProperty("statusNavigation")]
    public virtual ICollection<order> orders { get; set; } = new List<order>();
}