// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Living_Fountain.Models;

[Table("products", Schema = "living_fountain")]
public partial class product
{
    [Key]
    [StringLength(2)]
    public string code { get; set; }

    [StringLength(20)]
    public string product_desc { get; set; }

    [Column(TypeName = "decimal(2, 0)")]
    public decimal price { get; set; }

    [InverseProperty("product_codeNavigation")]
    public virtual ICollection<order> orders { get; set; } = new List<order>();
}