// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Living_Fountain.Models;

[Table("salary_types", Schema = "living_fountain")]
[Index("emp_type_code", Name = "emp_type_code")]
public partial class salary_type
{
    [Key]
    public int id { get; set; }

    [StringLength(1)]
    public char emp_type_code { get; set; }

    [Column(TypeName = "decimal(3, 0)")]
    public decimal amount { get; set; }

    [Required]
    [StringLength(20)]
    public string salary_desc { get; set; }

    [ForeignKey("emp_type_code")]
    [InverseProperty("salary_types")]
    public virtual employee_type emp_type_codeNavigation { get; set; }
}